blank_issues_enabled: false
contact_links:
  - name: "ðŸ“– Language guide"
    url: https://docs.quantinuum.com/guppy/language_guide/language_guide_index.html
    about: Read the language guide
  - name: "ðŸ“’ Example notebooks"
    url: https://github.com/Quantinuum/guppylang/tree/main/examples
    about: Explore example notebooks
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/Quantinuum/guppylang/discussions
    about: Ask questions and discuss ideas with the community
